{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adflow",
    "module": "core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.1.0.aar",
          "url": "core-0.1.0.aar",
          "size": 69855,
          "sha512": "27685183efe985f2bc8c02b75c09cd4499f3fd8f81f7d3b936ea6413a65174115d47dfa446e415e22008f8707a50c94f3c49096897daff636d7ae5b4899d6931",
          "sha256": "4d7c90f30b74ecbdadc7517b7f32948ddaf46b97342f1abe50fdb871585af56e",
          "sha1": "67be65b7b2bc880901c4a482d23f5a147ea7a564",
          "md5": "55d230dcac3ad364e5500cc88132abd4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.1.0.aar",
          "url": "core-0.1.0.aar",
          "size": 69855,
          "sha512": "27685183efe985f2bc8c02b75c09cd4499f3fd8f81f7d3b936ea6413a65174115d47dfa446e415e22008f8707a50c94f3c49096897daff636d7ae5b4899d6931",
          "sha256": "4d7c90f30b74ecbdadc7517b7f32948ddaf46b97342f1abe50fdb871585af56e",
          "sha1": "67be65b7b2bc880901c4a482d23f5a147ea7a564",
          "md5": "55d230dcac3ad364e5500cc88132abd4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.1.0-sources.jar",
          "url": "core-0.1.0-sources.jar",
          "size": 20889,
          "sha512": "65397d24fa56481fa2a050addea2bb42523e76e926481be7aef8e59532d706b06cf29b07be0a731a6a87adaccf92d4c89f324e1f7f0da766fdfafb8d04ee0b56",
          "sha256": "cecd6cb00f11e6b2e5c1976f47441c950ff1b4af55ab4ae3ff1fc193970ce35d",
          "sha1": "797173ee9e36f0074c303f6c886544fa9c5f533a",
          "md5": "b48f45ebbe6b11968642b062ebc68c48"
        }
      ]
    }
  ]
}
